# Generated by Django 3.2.12 on 2022-03-30 17:32

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name of client')),
                ('surname', models.CharField(max_length=30, verbose_name='Surname of client')),
                ('gender', models.CharField(choices=[('м', 'мужской'), ('ж', 'женский')], max_length=1, verbose_name='Gender of client')),
                ('email', models.EmailField(max_length=200, verbose_name='Email of client')),
                ('photo', models.ImageField(upload_to='clients/static/clients/media', verbose_name='Image of client')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('liked_users', models.ManyToManyField(related_name='liked_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
